# Required Software 

At this time, the Internal Peer Code Review Form requires the [Desktop App Version of Microsoft Word 365]{.mark}. This software is provided by the university at no cost. Training materials provided by IT can be found at the [Microsoft 365 at UTHealth webpage](https://inside.uth.edu/m365/). Details about how to access the student provided copies of this software are listed on the [Available Technology section of the Information Technology page on the mySPH SharePoint](https://uthtmc.sharepoint.com/sites/SPH-IT/SitePages/Available-Technology.aspx#office-365). The mobile app version and web app versions of Microsoft Word 365 do not allow interaction with fillable form fields. 

Review of code otherwise has similar software requirements to the writing and creation of the code. Microsoft OneDrive, a web browser, an [Integrated Development Environment](https://en.wikipedia.org/wiki/Integrated_development_environment) (IDE) (most commonly [RStudio](https://posit.co/download/rstudio-desktop/) for coding in R), the university [Virtual Private Network](https://med.uth.edu/msit/troubleshooting-vpn-and-remote-desktop-connections/) (VPN), and a stable internet connection are the most common requirements. 